#!/bin/bash
#test option force is set
force=0
if [ "$1" == "-f" ] && [ "$1" == "--force" ] && [ "$2" == "-f" ] && [ "$2" == "--force" ]; then
    force=1
fi
if [[ `git status --porcelain` ]] && [ force==1 ] ; then
    # test si runtests est présent
    if [ -f runtests.sh ]; then
        ./runtests
    fi
  
    git add .
    git commit -m "$1"
    git submodule foreach "git add . && gcp '$1'"
    git add .
    git commit -m "$1"
    git push
    git push --tags
else
    echo "no modifs ;-)"
fi
