#!/bin/bash
# Get a list of all branches
branches=$(git branch | sed 's/*//g')

# Merge all branches into main
for branch in $branches; do
  git merge --no-ff $branch main  --commit --no-edit
  git branch -d $branch
  # delete branch remotely
  git push origin --delete $branch
done
