#!/bin/bash

function show_usage (){
    printf "Usage: $0 [options ]\n"
    printf "\n"
    printf "Options:\n"
    printf " -f|--force, Force push\n"
    printf " -p|--passtest, Pass tests\n"
    printf " -h|--help, Print help\n"
    
    return 0
}



force=0
passtest=0

#test option force is set
for i in $@
do
    case $i in
        --force| -f)
            force=1
            shift
        ;;
        --passtest| -p)
            passtest=1
            shift
        ;;
        --help| -h)
            show_usage
            shift
        ;;
    esac
    shift
done

if [ ! -d "tests" ]; then
     passtest=1
fi

if [[ `git status --porcelain` ]] || [ $force == 1 ]  ; then
    if [ -f bin/phpunit ] && [ $passtest == 0 ] ; then
        echo "Running tests"
        CURRENT=`pwd`
        BASENAME=`basename "$CURRENT"`
        docker exec -it "$BASENAME" bin/phpunit
    fi
    if [ $? -ne 0 ]; then
        echo "ERREUR DANS LES TESTS ARRET" && exit
    else
        git add .
        oc config set description=true
        oc 
        git submodule foreach "git add . && oc config set description=true && gop "
        git add .
        oc 
        git push --tags
    fi
else
    echo "no modifs ;-)"
fi
