#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Usage: [-h] [commit_message] - stages, commits, and pushes changes, then deploys with ask""
        exit 0
    fi
done
git add .
git commit -m "$1"
git push
ask deploy
