#!/bin/bash
if [[ "$1" == "-h" ]]; then
    echo "Description : Script $0 (ajoutez une description ici)"
    echo "Usage : $0 [options]"
    echo "Exemple : $0"
    exit 0
fi
git submodule deinit $1
git rm --cached -r $1 -f
sudo rm .git/modules/$1 -R
sudo rm -R $1


if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi
if [ -f .env.local ]; then
    export $(grep -v '^#' .env.local | xargs)
fi
base=('./node_modules/' './vendor/'  './var/'  './.git'  './public/'  './backup' './docker-compose.yml')
exclude=$(printf " --exclude %s" "${base[@]}")
exclude=${exclude:1}
if  [ -n "$BACKUP_URL" ]; then
    if [ -z $BACKUP_URL ]; then
        echo "no parameters "
    else
        case "$1" in
            full )
            duplicity --no-encryption full . $BACKUP_URL --include './public/index.php' --include './public/uploads/.licence' --include './public/media/.licence' --exclude './docker-compose.yml' --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/' ;;
            local )
            duplicity --no-encryption full . file:///agarder/duplicity/$result/ --include './public/index.php' --include './public/uploads/.licence' --include './public/media/.licence' --exclude './docker-compose.yml' --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/' ;;
            * )
            duplicity --no-encryption incr . $BACKUP_URL --include './public/index.php' --include './public/uploads/.licence' --include './public/media/.licence' --exclude './docker-compose.yml' --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/'  ;;
        esac
        
    fi
    
    #duplicity incr . $BACKUP_URL --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/' --exclude './backup' --no-encryption --dry-run
    
else
    echo "parameters empty in .env, get BACKUP_URL"
fi

