#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Backup script using duplicity (params: full, local, or none for incremental)\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Backup script using duplicity (params: full, local, or none for incremental)""
        exit 0
    fi
done
result=${PWD##*/}


if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi
if [ -f .env.local ]; then
    export $(grep -v '^#' .env.local | xargs)
fi
base=('./node_modules/' './vendor/'  './var/'  './.git'  './public/'  './backup' './docker-compose.yml')
exclude=$(printf " --exclude %s" "${base[@]}")
exclude=${exclude:1}
if  [ -n "$BACKUP_URL" ]; then
    if [ -z $BACKUP_URL ]; then
        echo "no parameters "
    else
        case "$1" in
            full )
            duplicity --no-encryption full . $BACKUP_URL --include './public/index.php' --include './public/uploads/.licence' --include './public/media/.licence' --exclude './docker-compose.yml' --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/' ;;
            local )
            duplicity --no-encryption full . file:///agarder/duplicity/$result/ --include './public/index.php' --include './public/uploads/.licence' --include './public/media/.licence' --exclude './docker-compose.yml' --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/' ;;
            * )
            duplicity --no-encryption incr . $BACKUP_URL --include './public/index.php' --include './public/uploads/.licence' --include './public/media/.licence' --exclude './docker-compose.yml' --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/'  ;;
        esac
        
    fi
    
    #duplicity incr . $BACKUP_URL --exclude './node_modules/' --exclude './vendor/' --exclude './var/' --exclude './.git' --exclude './public/' --exclude './backup' --no-encryption --dry-run
    
else
    echo "parameters empty in .env, get BACKUP_URL"
fi

