#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Sets CAP_NET_BIND_SERVICE capability on Caddy binary to allow binding to privileged ports (<1024). Usage: [-h] [-v]\""
        exit 0
    fi
done
sudo setcap 'cap_net_bind_service=+ep' $(which caddy)
