#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Description: Display the autosaved Caddyfile from the caddy container. Parameters: none."
        exit 0
    fi
done
docker exec -it caddy cat config/caddy/Caddyfile.autosave
