#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Sets CAP_NET_BIND_SERVICE capability on Caddy binary to allow binding to privileged ports (<1024). No parameters.\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Sets CAP_NET_BIND_SERVICE capability on Caddy binary to allow binding to privileged ports (<1024). No parameters.""
        exit 0
    fi
done
sudo setcap 'cap_net_bind_service=+ep' $(which caddy)
