#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Usage: $(basename "$0") [container-name] [shell-type] - Exec into a PHP container's shell (default: current dir name and bash).""
        exit 0
    fi
done
result=${PWD##*/}
name=${1:-$result}    
bash=${2:-bash}
docker exec -i -t $name-php-1 /bin/$bash 
