#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Usage: $(basename \"$0\") [-h] [container_name] [shell_type] - Attach to a Docker container's shell (default: current directory name, bash).\""
        exit 0
    fi
done

result=${PWD##*/}
name=${1:-$result}    
bash=${2:-bash}
docker exec -i -t $name /bin/$bash 
