#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Run docker-compose with given arguments (e.g., up, down, build, logs, etc.).\""
        exit 0
    fi
done
docker compose $*
