#!/bin/bash
if [[ "$1" == "-h" ]]; then
    echo "Description : Script $0 (ajoutez une description ici)"
    echo "Usage : $0 [options]"
    echo "Exemple : $0"
    exit 0
fi
git submodule deinit $1
git rm --cached -r $1 -f
sudo rm .git/modules/$1 -R
sudo rm -R $1

set -e

# Détection de la commande docker compose
if command -v docker-compose &> /dev/null; then
    COMPOSE="docker-compose"
elif docker compose version &> /dev/null; then
    COMPOSE="docker compose"
else
    echo "Erreur : ni docker-compose ni docker compose n'est installé."
    exit 1
fi

# Fichiers à vérifier dans cet ordre
CANDIDATES=(
  "docker-compose.yml"
  "docker-compose.yaml"
  "docker-compose.override.yml"
  "docker-compose.override.yaml"
  "docker-compose.local.yml"
  "docker-compose.local.yaml"
  "compose.yml"
  "compose.yaml"
  "compose.override.yml"
  "compose.override.yaml"
  "compose.local.yml"
  "compose.local.yaml"
)

FILES=""
for FILE in "${CANDIDATES[@]}"; do
    if [[ -f "$FILE" ]]; then
        FILES="$FILES -f $FILE"
    fi
done

if [[ -z "$FILES" ]]; then
    echo "Aucun fichier de configuration Docker Compose trouvé."
    exit 1
fi

# Exécution
echo "Commande exécutée : $COMPOSE $FILES up -d"
$COMPOSE $FILES up -d
