#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Install gnome-tweak-tool: [-h] (no parameters)\""
        exit 0
    fi
done
sudo apt install gnome-tweak-tool

