#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Stop and remove all Docker containers (-h for help)""
        exit 0
    fi
done
#stop all containers:
docker kill $(docker ps -q) 

#remove all containers
docker rm $(docker ps -a -q)

