#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Stop and remove a Docker container; parameters: <container_name> [-h|--help]"
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Stop and remove a Docker container; parameters: <container_name>"
        exit 0
    fi
done
docker stop $1 || true
docker rm $1 || true
