#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Stop and remove a Docker container. Parameters: <container_name>"
        exit 0
    fi
done
docker stop $1 || true
docker rm $1 || true
