#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Display Docker container logs continuously or a specified number of lines. Parameters: [container_name] [--tail N]\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Display Docker container logs continuously or a specified number of lines. Parameters: [container_name] [--tail N]"
        exit 0
    fi
done
# Variables par défaut
nombre_de_logs=10
nom_du_docker=""

# Si un argument est fourni, il s'agit du nom du conteneur Docker
if [ -n "$1" ]; then
    nom_du_docker=$1
else
    nom_du_docker=$(basename "$(pwd)") # Nom du répertoire en cours par défaut si aucun argument n'est fourni
fi

# Affichage continu par défaut
docker logs --follow "$nom_du_docker" 2>&1
