#!/bin/bash
if [[ "$1" == "-h" ]]; then echo "Affiche les logs d'un conteneur Docker (paramètre: NOM_CONTENEUR, optionnel, défaut: nom du répertoire courant)."; exit 0; fi

# Variables par défaut
nombre_de_logs=10
nom_du_docker=""

# Si un argument est fourni, il s'agit du nom du conteneur Docker
if [ -n "$1" ]; then
    nom_du_docker=$1
else
    nom_du_docker=$(basename "$(pwd)") # Nom du répertoire en cours par défaut si aucun argument n'est fourni
fi

# Affichage continu par défaut
docker logs --follow "$nom_du_docker" 2>&1