#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Restart systemd-resolved service; params: [-h for help]""
        exit 0
    fi
done
sudo service systemd-resolved restart
