#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Restart systemd-resolved service; usage: [-h]\""
        exit 0
    fi
done
sudo service systemd-resolved restart
