#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Clean up unused Docker objects (containers, images, volumes, networks) - accepts no parameters.\""
        exit 0
    fi
done
docker system prune -a --volumes -f
