#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Clean up unused Docker objects (containers, images, volumes, networks) -f: force"
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Clean up unused Docker objects (containers, images, volumes, networks) -f: force""
        exit 0
    fi
done
docker system prune -a --volumes -f
