#!/bin/bash
if [[ "$1" == "-h" ]]; then
    echo "Description : Script $0 (ajoutez une description ici)"
    echo "Usage : $0 [options]"
    echo "Exemple : $0"
    exit 0
fi
git submodule deinit $1
git rm --cached -r $1 -f
sudo rm .git/modules/$1 -R
sudo rm -R $1

# Récupérer le nom du dossier courant
result=${PWD##*/}

# Vérifier si l'option `-c` est fournie
if [ "$1" == "-c" ]; then
  shift  # Supprimer `-c` des arguments
  docker exec -it "$result" sh -c "$@"
  exit 0
fi

# Utiliser le premier argument comme nom du conteneur, sinon utiliser le nom du dossier courant
name=${1:-$result}

# Vérifier si des commandes supplémentaires sont passées
if [ "$#" -gt 1 ]; then
  docker exec -it "$result" "$@"
else
  docker exec -it "$name" /bin/sh
fi
