#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Usage: [-h] [-c command] [container_name] [command] - Execute command in or enter a Docker container, defaulting to current directory name\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Usage: [-h] [-c command] [container_name] [command] - Execute command in or enter a Docker container, defaulting to current directory name""
        exit 0
    fi
done

# Récupérer le nom du dossier courant
result=${PWD##*/}

# Vérifier si l'option `-c` est fournie
if [ "$1" == "-c" ]; then
  shift  # Supprimer `-c` des arguments
  docker exec -it "$result" sh -c "$@"
  exit 0
fi

# Utiliser le premier argument comme nom du conteneur, sinon utiliser le nom du dossier courant
name=${1:-$result}

# Vérifier si des commandes supplémentaires sont passées
if [ "$#" -gt 1 ]; then
  docker exec -it "$result" "$@"
else
  docker exec -it "$name" /bin/sh
fi
