#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Display disk usage for current directory contents (sorted by size) and overall disk space; no parameters.\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Display disk usage for current directory contents (sorted by size) and overall disk space; no parameters.""
        exit 0
    fi
done
du -sh ./* | sort -hr
df -h
