#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Set CPU governor to performance mode for cores 0-7.\" Parameters: none."
        exit 0
    fi
done
for i in {0..7};
do sudo cpufreq-set -c $i -g performance;
done;
