#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Usage: $0 [-h] <file> <message> - Stages, commits, and pushes changes to Git.""
        exit 0
    fi
done
git add "$1"
git commit -m "$2"
git push
