#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Usage: $0 [-h] <commit_message> - Stage all changes and commit with the given message.""
        exit 0
    fi
done
git add .
git commit -m "$1"
