#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Usage: $0 [-h|--help] - Checkout main branch in all Git submodules\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Usage: $0 [-h] - Checkout main branch in all Git submodules""
        exit 0
    fi
done
git submodule foreach git checkout main 
