#!/bin/bash
if [[ "$1" == "-h" ]]; then
    echo "Description : Script $0 (ajoutez une description ici)"
    echo "Usage : $0 [options]"
    echo "Exemple : $0"
    exit 0
fi
git submodule deinit $1
git rm --cached -r $1 -f
sudo rm .git/modules/$1 -R
sudo rm -R $1
# Get a list of all branches
branches=$(git branch | sed 's/*//g')

# Merge all branches into main
for branch in $branches; do
  git merge --no-ff $branch main  --commit --no-edit
  git branch -d $branch
  # delete branch remotely
  git push origin --delete $branch
done
