#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Merge all local and remote branches into main, then delete them (-h for help)\" [parameters: none]"
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Merge all local and remote branches into main, then delete them (-h for help)" [parameters: none]"
        exit 0
    fi
done
# Get a list of all branches
branches=$(git branch | sed 's/*//g')

# Merge all branches into main
for branch in $branches; do
  git merge --no-ff $branch main  --commit --no-edit
  git branch -d $branch
  # delete branch remotely
  git push origin --delete $branch
done
