#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Reset local changes, clean untracked files, and pull latest changes. Parameters: None."
        exit 0
    fi
done
git reset --hard
git clean -df
git pull
