#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Delete a Git branch locally and remotely. Parameters: <branch_name>""
        exit 0
    fi
done
# delete branch locally
git branch -d $1

# delete branch remotely
git push origin --delete $1
