#!/bin/bash
if [[ "$1" == "-h" ]]; then
    echo "Description : Script $0 (ajoutez une description ici)"
    echo "Usage : $0 [options]"
    echo "Exemple : $0"
    exit 0
fi
git submodule update --init --recursive
