#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Fetch, track all remote branches, pull updates, and merge all branches in each submodule. Parameters: none.""
        exit 0
    fi
done
git submodule foreach "git fetch --all && git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done && git pull --all && gitMergeAll

