#!/bin/bash

if [ -f ".gitmodules" ]; then

git submodule foreach git checkout main 
git submodule foreach git pull

if [ -d "src/Command/crudmick" ]; then 
  cd src/Command/crudmick
  git pull
fi

fi
