#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Configures all git submodules to use rebase on pull; no parameters.\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Configures all git submodules to use rebase on pull; no parameters.""
        exit 0
    fi
done
git submodule foreach git config pull.rebase true 
