#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Initialize and update git submodules recursively (-h for help)." Parameters: none."
        exit 0
    fi
done
git submodule update --init --recursive
