#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Check Git and submodule statuses. Parameters: none."
        exit 0
    fi
done
git status
git submodule foreach git status
