#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Usage: [-h] [-p port] - Starts a simple HTTP server on specified port (default: 8000) and displays access URL.\""
        exit 0
    fi
done
http-server -p 8000 .
echo "access by http://my-ip:8000"
