#!/bin/bash
# Optimiser les fichiers PNG, GIF, TIFF, et BMP avec optipng
find . -type f \( -iname "*.png" -o -iname "*.PNG" -o -iname "*.gif" -o -iname "*.GIF" -o -iname "*.tif" -o -iname "*.TIF" -o -iname "*.tiff" -o -iname "*.TIFF" -o -iname "*.bmp" -o -iname "*.BMP" \) -exec optipng {} \;

# Optimiser les fichiers JPG et JPEG avec jpegoptim
find . -type f \( -iname "*.jpg" -o -iname "*.JPG" -o -iname "*.jpeg" -o -iname "*.JPEG" \) -exec jpegoptim -o 5 {} \;
