#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Resize all JPG/JPEG/PNG images in a directory to specified dimensions, e.g., 800x600. Parameters: <dimensions> [directory].\""
        exit 0
    fi
done
for file in "$arg"/*.{jpg,jpeg,png,JPEG,JPG,PNG}; do convert $file -resize $1 $file; done
