#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Optimize image files (PNG, GIF, TIFF, BMP, JPG, JPEG) in current directory and subdirectories using optipng and jpegoptim.\" Parameters: none."
        exit 0
    fi
done
# Optimiser les fichiers PNG, GIF, TIFF, et BMP avec optipng
find . -type f \( -iname "*.png" -o -iname "*.PNG" -o -iname "*.gif" -o -iname "*.GIF" -o -iname "*.tif" -o -iname "*.TIF" -o -iname "*.tiff" -o -iname "*.TIFF" -o -iname "*.bmp" -o -iname "*.BMP" \) -exec optipng {} \;

# Optimiser les fichiers JPG et JPEG avec jpegoptim
find . -type f \( -iname "*.jpg" -o -iname "*.JPG" -o -iname "*.jpeg" -o -iname "*.JPEG" \) -exec jpegoptim -o 5 {} \;
