#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"List top 30 largest files in /, parameters: none\""
        exit 0
    fi
done
find / -type f -exec du -Sh {} + 2>/dev/null | sort -rh | head -n 30
