#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Show top 30 largest files/directories in /, sorted by size (-h human-readable, -S no subdirs, -r reverse, -n numeric sort)\""
        exit 0
    fi
done
du -Sh / 2>/dev/null | sort -rh | head -n 30
