#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"List top 30 largest files in /, parameters: none\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""List top 30 largest files in /, parameters: none""
        exit 0
    fi
done
find / -type f -exec du -Sh {} + 2>/dev/null | sort -rh | head -n 30
