#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Perform a ping scan (-sn) on the local network (192.168.1.0/24) using nmap with sudo.\" Parameters: [-h]"
        exit 0
    fi
done
sudo nmap -sn 192.168.1.0/24
