#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Perform a ping scan (-sn) on the local network (192.168.1.0/24) using sudo nmap." Parameters: [-h] [custom_network_range]"
        exit 0
    fi
done
sudo nmap -sn 192.168.1.0/24
