#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Count files in each subdirectory, sorted by count; parameters: none.\""
        exit 0
    fi
done
for i in *; do echo -n $i " " ; find $i |wc -l; done | sort -n -k2

