#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Search for files with 'conflicted' in their name (case-insensitive). Parameters: [directory].""
        exit 0
    fi
done
find -iname *conflicted*
