#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Usage: $(basename \"$0\") [-h] <port> - List processes listening on specified port; -h shows help.\""
        exit 0
    fi
done
sudo ss -nlp | grep :$1
