#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Usage: $(basename "$0") [-h] <port> - List processes listening on specified port.""
        exit 0
    fi
done
sudo ss -nlp | grep :$1
