#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Deploy and update project on remote server via SSH, using SERVER_CONNECT and SERVER_DIR from .env.\" Parameters: none (uses .env file)."
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Deploy and update project on remote server via SSH, using SERVER_CONNECT and SERVER_DIR from .env." Parameters: none (uses .env file)."
        exit 0
    fi
done
#connect at server by parameter in .env
#SERVER_CONNECT=user@ip or name
#SERVER_DIR=/home/.../...
#get parameters
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi
if [ -n "$SERVER_DIR" ] || [-n "$SERVER_CONNECT"]; then
    ssh $SERVER_CONNECT "cd $SERVER_DIR && git pull && sh maintenance.sh on && docker exec -i ${SERVER_DIR##*/} composer update && docker exec -i ${SERVER_DIR##*/} yarn install --force && docker exec -i ${SERVER_DIR##*/} yarn build && docker exec -i ${SERVER_DIR##*/} bin/console cache:clear && sh maintenance.sh off"

else
    echo "parameters empty in .env, get SERVER_CONNECT and SERVER_DIR"
fi
