#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Connect to a server and execute a command in a specified directory. Parameters: command (in quotes).\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo ""Connect to a server and execute a command in a specified directory. Parameters: command (in quotes).""
        exit 0
    fi
done
#connect at server by parameter in .env
#SERVER_CONNECT=user@ip or name
#SERVER_DIR=/home/.../...

#get parameters
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi
if [ -n "$SERVER_DIR" ] || [-n "$SERVER_CONNECT"]; then
    if [ $# -eq 0 ]; then
        echo "command between quotation mark "
    else
        ssh $SERVER_CONNECT "cd $SERVER_DIR && $1"
    fi
else
    echo "parameters empty in .env, get SERVER_CONNECT and SERVER_DIR"
fi
