#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Set all CPU cores to powersave mode: [-h]\""
        exit 0
    fi
done
for i in {0..7};
do sudo cpufreq-set -c $i -g powersave;
done;
