#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Convert SVG files to PNG with optional width (default: 1024). Usage: script.sh [width]"
        exit 0
    fi
done
#parameter 1 pour width sinon 1024 par defaut
width=${1:-1024}  
for i in *.svg; 
do inkscape -w "$width"  "$i" --export-filename "${i%svg}png";
done
