#!/bin/bash
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Set TTL value (64 for PC, 65 for Phone) - no parameters.\""
        exit 0
    fi
done
# Affiche l'aide si -h ou --help est présent n'importe où dans les arguments
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "Set TTL value (64 for PC, 65 for Phone) - no parameters."
        exit 0
    fi
done
my_dir="$(dirname "$0")"
source "$my_dir/lib.sh"
# ---------------------------------------------------------------------------- #
selections=(
"PC"
"Téléphone"
)
L_choice "Mettre le ttl pour " selected_choice "${selections[@]}"
if [[ $selected_choice == 0 ]]
then
sudo sysctl net.ipv4.ip_default_ttl=64
else
sudo sysctl net.ipv4.ip_default_ttl=65
fi
echo "ttl mis à $(sysctl -n net.ipv4.ip_default_ttl)"
