#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Usage: $(basename \"$0\") [-h] - Plays a series of beeps for 1 hour; no parameters required.\""
        exit 0
    fi
done
#/etc/modprobe.d/blacklist.con change #blacklist pcspkr to blacklist pcspkr
#or sudo modprobe pcspkr
sleep 1h
for n in 1 2 3 4 5 6 7 8 9 0; do
      for f in 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600; do
          beep -f $f -l 20
      done
done
