#!/bin/bash
for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        echo "\"Download a file from URL (parameter 1) with resuming support, optional rate limit (parameter 2, default: 300k), ignoring SSL, saving with original name.\" Parameters: <URL> [rate_limit]"
        exit 0
    fi
done
curl $1 -C - -k -O  --limit-rate ${2:-300k}
